services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb:/var/lib/mysql
  alpine:
    build:
      context: .
      dockerfile: alpine.Dockerfile
      args:
        SFTP_USER: ${SFTP_USER}
        SFTP_PASSWORD: ${SFTP_PASSWORD}
    restart: always
    ports:
      - 80
      - "${SFTP_PORT}:22"
    tty: true
    volumes:
      - ./html:/home/alpine/www
    labels:
      - traefik.enable=true
      - traefik.http.routers.alpine-${SFTP_USER}.rule=${DOMAIN}
      - traefik.http.routers.alpine-${SFTP_USER}.entrypoints=websecure
      - traefik.http.routers.alpine-${SFTP_USER}.tls=true
      - traefik.http.routers.alpine-${SFTP_USER}.tls.certresolver=le
      - traefik.http.services.alpine-${SFTP_USER}.loadbalancer.server.port=80
volumes:
  mariadb: {}
  alpine: {}
